<form action="/api/postresult" method="post">
    <input type="number" name="first" placeholder="первое число"/><br>
    <input type="number" name="second" placeholder="второе число"/><br>
    <input type="text" name="operation" placeholder="операция"/><br>
    <input type="submit" value="===="/>
<form/>
<p>${answer}<p/>
<br>
<br>
<br>
<a href="/api/history" >История<a/>
<br>
<a href="/api/profile" >Мой профиль<a/>